[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "laypatel13-data-visualizer"
version = "0.1.0"
description = "A colorful CLI tool to visualize CSV data using Matplotlib and Seaborn"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "Lay Patel", email = "lay.patel.1313@gmail.com"}
]
keywords = ["cli", "data", "visualizer", "matplotlib", "seaborn", "csv"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Environment :: Console",
]
dependencies = [
    "pandas>=2.0",
    "matplotlib>=3.8",
    "seaborn>=0.13",
    "colorama==0.4.6",
]

[project.scripts]
data-visualizer = "data_visualizer.main:main"

[project.urls]
Homepage = "https://github.com/laypatel13/data-visualizer"